services:
  db_master:
    image: postgres:16-alpine
    container_name: library_db_master
    restart: unless-stopped
    environment:
      POSTGRES_USER: libraryuser
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: librarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./db/init-master.sql:/docker-entrypoint-initdb.d/01-init.sql
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=10
      -c hot_standby=on
      -c max_connections=200
    networks:
      - p_network

  db_slave:
    image: postgres:16-alpine
    container_name: library_db_slave
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret123
    ports:
      - "5433:5432"
    volumes:
      - postgres_slave_data:/var/lib/postgresql/data
      - ./db/init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
    command: postgres -c hot_standby=on
    depends_on:
      - db_master
    networks:
      - p_network

  api_master:
    build:
      context: ./library_app
      dockerfile: ./api/Dockerfile
    container_name: library_api_master
    environment:
      - DB_URL=jdbc:postgresql://db_master:5432/librarydb
      - DB_USER=libraryuser
      - DB_PASSWORD=secret123
      - DB_READ_ONLY=false
      - PORT=8080
      - INSTANCE_NAME=api_master
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - db_master
      - loki
    logging:
      driver: "json-file"
    networks:
      - p_network

  api_slave1:
    build:
      context: ./library_app
      dockerfile: ./api/Dockerfile
    container_name: library_api_slave1
    environment:
      - DB_URL=jdbc:postgresql://db_master:5432/librarydb
      - DB_USER=readonlyuser
      - DB_PASSWORD=readonly123
      - DB_READ_ONLY=true
      - PORT=8081
      - INSTANCE_NAME=api_slave1
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - db_master
      - loki
    logging:
      driver: "json-file"
    networks:
      - p_network

  api_slave2:
    build:
      context: ./library_app
      dockerfile: ./api/Dockerfile
    container_name: library_api_slave2
    environment:
      - DB_URL=jdbc:postgresql://db_master:5432/librarydb
      - DB_USER=readonlyuser
      - DB_PASSWORD=readonly123
      - DB_READ_ONLY=true
      - PORT=8082
      - INSTANCE_NAME=api_slave2
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - db_master
      - loki
    logging:
      driver: "json-file"
    networks:
      - p_network

  api_mirror:
    build:
      context: ./library_app
      dockerfile: ./api/Dockerfile
    container_name: library_api_mirror
    environment:
      - DB_URL=jdbc:postgresql://db_master:5432/librarydb
      - DB_USER=readonlyuser
      - DB_PASSWORD=readonly123
      - DB_READ_ONLY=true
      - BASE_PATH=/mirror
      - PORT=8080
      - INSTANCE_NAME=api_mirror
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    depends_on:
      - db_slave
      - loki
    logging:
      driver: "json-file"
    networks:
      - p_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    user: "root"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3100/ready"]
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - p_network

  grafana:
    image: grafana/grafana:latest
    container_name: library_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SERVER_ROOT_URL=http://localhost:3000/monitoring
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - p_network
    depends_on:
      - loki


  adminer:
    image: adminer
    container_name: library_adminer
    restart: always
    ports:
      - "8084:8080"
    networks:
      - p_network

  nginx:
    image: nginx:alpine
    container_name: library_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
      - ./static:/var/www/project/static:ro
    depends_on:
      - api_master
      - api_slave1
      - api_slave2
      - api_mirror
      - grafana
    networks:
      - p_network

volumes:
  postgres_master_data:
  postgres_slave_data:
  grafana_data:
  nginx_logs:
  loki_data:

networks:
  p_network:
    driver: bridge